import { LM, LS } from ".";
import Logger from "./debug/Logger";
Logger.emergency("Test", [{ test: true, text: "My life" }]);
Logger.alert("Test", [{ test: true, text: "My life" }]);
Logger.critical("Test", [{ test: true, text: "My life" }]);
Logger.error("Test", [{ test: true, text: "My life" }]);
Logger.warning("Test", [{ test: true, text: "My life" }]);
Logger.notice("Test", [{ test: true, text: "My life" }]);
Logger.info("Test", [{ test: true, text: "My life" }]);
Logger.verbose("Test", [{ test: true, text: "My life" }]);
Logger.debug("Test", [{ test: true, text: "My life" }]);
Logger.whoCares("Test", [{ test: true, text: "My life" }]);
